language: rust

rust:
  - 1.43.0
  - 1.44.1
  - 1.45.1
  - stable
  - beta
  - nightly

matrix:
  include:
    # Rustfmt
    - rust: stable
      install:
        - rustup component add rustfmt-preview
      before_script:
        - cargo fmt --version
      script:
        - cargo fmt -- --check
      env:
        - CHECK_FORMAT=TRUE

    # Clippy
    - rust: stable
      install:
        - rustup component add clippy-preview
      script:
        # Fail if clippy output contains "error:" or "warning:"
        - cargo clippy 2>&1 | tee ./clippy.out && ! grep -qe  "error:\|warning:" ./clippy.out
      env:
        - CHECK_SYNTAX=TRUE

    # Test coverage
    - rust: nightly
      install:
        - RUSTFLAGS="--cfg procmacro2_semver_exempt" cargo install cargo-tarpaulin --force
      script:
        - cargo tarpaulin --ciserver travis-ci --coveralls $TRAVIS_JOB_ID
      env:
        - COVERAGE_CHECK=TRUE

script:
  - cargo test

cache:
  cargo: true

addons:
  apt:
    packages:
      - libssl-dev  # Required for tarpaulin
      - gcc
